import './globals.css'
import  './Navbar.js'
import './Footer.js'
import Navbar from './Navbar.js'
import Footer from './Footer.js'
// const Inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
